### ISSUE TITLE
Average chunks

### ISSUE THREAD

**Issue by chriswait** [EilidhHendry/author-similarity#16]
We can speed up some operations by storing "average" chunks for Author and Text models.

Once a text has been added, the average of all chunks should be computed and stored for the texts.
If an author's texts have changed, it's average chunk should be computed based on it's texts' chunks, and stored.

**Comment by EilidhHendry** [comment]
Commit ff47b34 create model fields for average chunk, functions to calculate them and an admin action to compute the average.

Still to do: 
-  If there's already an average chunk delete that chunk from the database
-  Don't use average chunks to train the classifier
-  When saving a Text's average chunk it calls the custom save method and so rechunks etc. We don't want to do this.

**Comment by chriswait** [comment]
Commit f77d5867fd6301981101fb116557f706af36b38e:
- remove existing averages before computing new ones

Commit ab5a8978c9d60ed069f0fd04925993e56652442d
- fixes issues I introduced in f77d5867fd6301981101fb116557f706af36b38e, where removing an existing average_chunk caused the Author or Text to be removed along with it because foreign keys etc still to improve this, sorry future self
- prevents using average chunks when training classifier, testing accuracy etc

**Comment by chriswait** [comment]
Todo:
- ~~Use django's really obviously useful on_delete=models.SET_NULL option, instead of doing whacky foreign key manipulation~~ - 6e145677663871f985b77ff9d545300e1d685a7d (migration actually added in c06db06f1e4b5177bd0713c8150ca9bf9e740112)
- ~~Move some of the averaging into a task~~ - 9b3561786b4bf92424eeb277a6dc31d8d8d7b7f9
- ~~Work out how to group the chunking tasks and run averaging after uploading a text~~ - 2f75c95a3155e1a79743f94007a7569fc9857c88

**Comment by chriswait** [comment]
483ab9f7fab8cf26a32478a3bd56427380a88d68 - we now compute the author's average chunk based on the average of their texts' chunks, which will be quicker.

Todo:
- ~~Ensure author averages are fairly up to date, probably using same strategy as classifier~~ - c06db06f1e4b5177bd0713c8150ca9bf9e740112

**Comment by chriswait** [comment]
When texts are saved, they:
- automatically compute their own averages
- tell the author's to update their own averages the next time we check for outdated authors

Thus, the system should keep its author averages up to date (every 10 minutes), and these are returned with classification feedback.

(_Did most of this in a few hours, changed the broker, added a result backend _and_ migrations... things will be broken..._)
